import {
  answersByQuestion,
  hackerQuestionsForStoredAnswers,
  questionsForType,
} from "@/lib/grading/questions";
import type { ApplicationType } from "@/lib/grading/types";
import type { OrganizerApplication } from "@/components/OrganizerDashboard";
import type { ReviewApplication, ReviewInfoField } from "@/components/OrganizerReviewClient";

type MockSeed = {
  id: string;
  type: ApplicationType;
  status: OrganizerApplication["status"];
  first_name: string;
  last_name: string;
  email: string;
  school_or_organization: string;
  answers: string[];
  info: ReviewInfoField[];
  submitted_at: string;
  average_score: number | null;
  grader_count: number;
  my_score: number | null;
  notification_sent_at: string | null;
  notification_error: string | null;
};

const SEEDS: MockSeed[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    type: "hacker",
    status: "pending",
    first_name: "Ava",
    last_name: "Chen",
    email: "ava.chen@example.com",
    school_or_organization: "Waterloo Collegiate Institute",
    submitted_at: "2026-03-12T18:22:00.000Z",
    average_score: null,
    grader_count: 0,
    my_score: null,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "Late buses make half my class miss first period. I would build a simple school-route tracker that only shows the two buses that actually stop near us, with a leave-now alert so students are not guessing from the city transit app.",
      "I taught myself scraping by rebuilding a bus tracker overnight. I started with one broken script, read docs until each error made sense, and shipped a tiny tool my brother still uses.",
    ],
    info: [
      { label: "Preferred name", value: "Ava" },
      { label: "Pronouns", value: "she/her" },
      { label: "T-shirt size", value: "M" },
      { label: "City", value: "Waterloo" },
      { label: "Province", value: "Ontario" },
      { label: "Dietary restrictions", value: "Vegetarian" },
      { label: "Accessibility accommodations", value: "None" },
      { label: "Grade", value: "11" },
      { label: "Graduation year", value: "2027" },
      { label: "Coding experience", value: "Intermediate" },
      { label: "Goals", value: "Build my first project, Meet other students interested in tech, Work with mentors" },
      { label: "Want to see at HTS", value: "More beginner-friendly workshops on shipping a demo." },
      { label: "Favourite song", value: "Motion Sickness — Phoebe Bridgers" },
      { label: "LinkedIn / Portfolio", value: "https://linkedin.com/in/ava-chen-mock" },
      { label: "GitHub / Devpost", value: "https://github.com/ava-chen-mock" },
      { label: "Heard about HTS", value: "Instagram" },
    ],
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    type: "hacker",
    status: "pending",
    first_name: "Jordan",
    last_name: "Patel",
    email: "jordan.patel@example.com",
    school_or_organization: "Cameron Heights",
    submitted_at: "2026-03-14T09:05:00.000Z",
    average_score: 7.8,
    grader_count: 2,
    my_score: 8.0,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "Broken headphones pile up in lost and found. I would design a tiny repair station app that logs common fixes and parts so students can revive gear instead of tossing it.",
      "I learned to solder from YouTube after three pairs of classmates' headphones died. I practiced on scrap wires first, failed a lot, then fixed the real ones.",
    ],
    info: [
      { label: "Preferred name", value: "Jordan" },
      { label: "Pronouns", value: "they/them" },
      { label: "T-shirt size", value: "L" },
      { label: "City", value: "Kitchener" },
      { label: "Province", value: "Ontario" },
      { label: "Dietary restrictions", value: "Halal, Nut allergy" },
      { label: "Dietary (other)", value: "No tree nuts; sesame is fine." },
      { label: "Accessibility accommodations", value: "Quiet space for breaks" },
      { label: "Grade", value: "12" },
      { label: "Graduation year", value: "2026" },
      { label: "Coding experience", value: "Novice" },
      { label: "Goals", value: "Improve my coding skills, Find teammates, Try something completely new" },
      { label: "Want to see at HTS", value: "Hardware lending and soldering help." },
      { label: "Favourite song", value: "Sunflower — Rex Orange County" },
      { label: "LinkedIn / Portfolio", value: "https://linkedin.com/in/jordan-patel-mock" },
      { label: "GitHub / Devpost", value: "https://devpost.com/jordan-patel-mock" },
      { label: "Heard about HTS", value: "Friend" },
    ],
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    type: "mentor",
    status: "pending",
    first_name: "Sam",
    last_name: "Okoye",
    email: "sam.okoye@example.com",
    school_or_organization: "University of Waterloo",
    submitted_at: "2026-03-10T15:40:00.000Z",
    average_score: null,
    grader_count: 0,
    my_score: null,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "Python, TypeScript, FastAPI, Postgres, and beginner-friendly React. Strongest at helping teams structure a first backend.",
      "I have mentored at two high-school hackathons and run a small open-source CLI used by local coding clubs.",
      "I want to help beginners ship something they are proud of by Sunday and leave with clearer debugging habits.",
    ],
    info: [
      { label: "Program / year", value: "Software Engineering, 3B" },
      { label: "University / college", value: "University of Waterloo" },
      { label: "LinkedIn / Portfolio / GitHub", value: "https://linkedin.com/in/sam-okoye-mock" },
      { label: "Mentoring areas", value: "Programming / Software Development, Web Development, Product Development" },
      { label: "Available for full event", value: "Yes" },
      { label: "Times unavailable", value: "Saturday 2–4pm lecture conflict" },
    ],
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    type: "hacker",
    status: "rejected",
    first_name: "Riley",
    last_name: "Nguyen",
    email: "riley.nguyen@example.com",
    school_or_organization: "Eastwood Collegiate",
    submitted_at: "2026-03-08T11:10:00.000Z",
    average_score: 4.2,
    grader_count: 1,
    my_score: 4.2,
    notification_sent_at: "2026-03-16T09:00:00.000Z",
    notification_error: null,
    answers: [
      "Lunch lines are chaotic. I would try a simple queue display so people know which line is shortest.",
      "I followed a few coding tutorials and made a personal homepage. I mostly copied examples until something loaded.",
    ],
    info: [
      { label: "Preferred name", value: "Riley" },
      { label: "Pronouns", value: "he/him" },
      { label: "T-shirt size", value: "S" },
      { label: "City", value: "Kitchener" },
      { label: "Province", value: "Ontario" },
      { label: "Dietary restrictions", value: "None" },
      { label: "Grade", value: "10" },
      { label: "Graduation year", value: "2028" },
      { label: "Coding experience", value: "Complete Beginner" },
      { label: "Goals", value: "Learn how to code, See what a hackathon is like" },
      { label: "Want to see at HTS", value: "A chill intro track." },
      { label: "Favourite song", value: "Blinding Lights — The Weeknd" },
      { label: "LinkedIn / Portfolio", value: "" },
      { label: "GitHub / Devpost", value: "https://github.com/riley-nguyen-mock" },
      { label: "Heard about HTS", value: "Friend" },
    ],
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    type: "mentor",
    status: "accepted",
    first_name: "Morgan",
    last_name: "Singh",
    email: "morgan.singh@example.com",
    school_or_organization: "Wilfrid Laurier University",
    submitted_at: "2026-03-09T20:00:00.000Z",
    average_score: 8.5,
    grader_count: 1,
    my_score: 8.5,
    notification_sent_at: "2026-03-16T10:00:00.000Z",
    notification_error: null,
    answers: [
      "JavaScript, Figma, product scoping, and pitching. Comfortable pairing on UI polish and demo storytelling.",
      "I lead a campus coding club and mentor first-years through their first group projects.",
      "I want to give high-school hackers the same patient feedback I wish I had at their age.",
    ],
    info: [
      { label: "Program / year", value: "Business & Computer Science, Year 3" },
      { label: "University / college", value: "Wilfrid Laurier University" },
      { label: "LinkedIn / Portfolio / GitHub", value: "https://linkedin.com/in/morgan-singh-mock" },
      { label: "Mentoring areas", value: "UI/UX & Design, Pitching / Presentations, Entrepreneurship / Business" },
      { label: "Available for full event", value: "Yes" },
    ],
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    type: "hacker",
    status: "pending",
    first_name: "Casey",
    last_name: "Brooks",
    email: "casey.brooks@example.com",
    school_or_organization: "Huron Heights",
    submitted_at: "2026-03-16T08:00:00.000Z",
    average_score: null,
    grader_count: 0,
    my_score: null,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "Our greenhouse club forgets to water plants. I would build a cheap soil-sensor reminder that texts whoever is on duty that week.",
      "I learned circuits by frying two sensors first. Then I slowed down, sketched the wiring, and got a working plant reminder for my roommate.",
    ],
    info: [
      { label: "Preferred name", value: "Casey" },
      { label: "Pronouns", value: "she/they" },
      { label: "T-shirt size", value: "M" },
      { label: "City", value: "Cambridge" },
      { label: "Province", value: "Ontario" },
      { label: "Dietary restrictions", value: "Gluten-free" },
      { label: "Accessibility accommodations", value: "None" },
      { label: "Grade", value: "11" },
      { label: "Graduation year", value: "2027" },
      { label: "Coding experience", value: "Intermediate" },
      { label: "Goals", value: "Build my first project, Learn about AI, Win prizes" },
      { label: "Want to see at HTS", value: "Hardware kits and sensor help desks." },
      { label: "Favourite song", value: "Electric Feel — MGMT" },
      { label: "LinkedIn / Portfolio", value: "https://caseybrooks.dev" },
      { label: "GitHub / Devpost", value: "https://github.com/casey-brooks-mock" },
      { label: "Heard about HTS", value: "School club" },
    ],
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    type: "hacker",
    status: "pending",
    first_name: "Mock",
    last_name: "Mock",
    email: "mock.mock@example.com",
    school_or_organization: "Mock High School",
    submitted_at: "2026-03-18T12:00:00.000Z",
    average_score: null,
    grader_count: 0,
    my_score: null,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "I would use phone audio to classify bird calls around campus so the eco club can map which species show up near noisy roads.",
      "I taught myself browser extensions by shipping a calendar duplicate highlighter. I broke it five times, read MDN, and shipped an ugly version that still saves me.",
    ],
    info: [
      { label: "Preferred name", value: "Mock" },
      { label: "Pronouns", value: "they/them" },
      { label: "T-shirt size", value: "L" },
      { label: "City", value: "Toronto" },
      { label: "Province", value: "Ontario" },
      { label: "Dietary restrictions", value: "Vegetarian, Other" },
      { label: "Dietary (other)", value: "No mushrooms." },
      { label: "Accessibility accommodations", value: "Other" },
      { label: "Accessibility (other)", value: "Prefer written instructions for workshops." },
      { label: "Grade", value: "12" },
      { label: "Graduation year", value: "2026" },
      { label: "Coding experience", value: "Advanced" },
      { label: "Goals", value: "Improve my coding skills, Meet other students interested in tech, Work with mentors" },
      { label: "Want to see at HTS", value: "ML intro workshop and demo coaching." },
      { label: "Favourite song", value: "Nightcall — Kavinsky" },
      { label: "LinkedIn / Portfolio", value: "https://linkedin.com/in/mock-mock" },
      { label: "GitHub / Devpost", value: "https://github.com/mock-mock" },
      { label: "Heard about HTS", value: "Other" },
      { label: "Heard about HTS (other)", value: "Discord server" },
      { label: "Other comments", value: "Happy to help first-time hackers debug." },
    ],
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    type: "judge",
    status: "pending",
    first_name: "Alex",
    last_name: "Rivera",
    email: "alex.rivera@example.com",
    school_or_organization: "Northwind Labs · Staff Engineer",
    submitted_at: "2026-03-17T16:30:00.000Z",
    average_score: null,
    grader_count: 0,
    my_score: null,
    notification_sent_at: null,
    notification_error: null,
    answers: [
      "A strong project solves a real user problem, ships a working demo, and shows clear tradeoffs the team made under time pressure.",
      "I build developer tools at Northwind and previously mentored university hackathon teams on product scoping and demo polish.",
      "I judged a campus pitch night last year and a high-school science fair software category the year before.",
    ],
    info: [
      { label: "Company / organization", value: "Northwind Labs" },
      { label: "Job title", value: "Staff Engineer" },
      { label: "LinkedIn", value: "https://linkedin.com/in/alex-rivera" },
      { label: "Industry / field", value: "Developer tools" },
      { label: "Expertise", value: "Software / Technology, AI / Machine Learning, Product Management" },
      { label: "Years of experience", value: "6-10" },
      { label: "Available for full judging period", value: "Yes" },
    ],
  },
];

export function getMockOrganizerApplications(): OrganizerApplication[] {
  return SEEDS.map((seed) => ({
    id: seed.id,
    type: seed.type,
    status: seed.status,
    first_name: seed.first_name,
    last_name: seed.last_name,
    email: seed.email,
    school_or_organization: seed.school_or_organization,
    details: null,
    answers: seed.answers,
    submitted_at: seed.submitted_at,
    notification_sent_at: seed.notification_sent_at,
    notification_error: seed.notification_error,
    average_score: seed.average_score,
    grader_count: seed.grader_count,
    my_score: seed.my_score,
  }));
}

export function getMockReviewApplication(id: string): ReviewApplication | null {
  const seed = SEEDS.find((entry) => entry.id === id);
  if (!seed) return null;
  const questions =
    seed.type === "hacker"
      ? hackerQuestionsForStoredAnswers(seed.answers)
      : questionsForType(seed.type);
  return {
    id: seed.id,
    type: seed.type,
    status: seed.status,
    first_name: seed.first_name,
    last_name: seed.last_name,
    email: seed.email,
    school_or_organization: seed.school_or_organization,
    details: null,
    answers: answersByQuestion(seed.type, seed.answers, questions),
    info: seed.info.filter((field) => field.value.trim()),
    submitted_at: seed.submitted_at,
  };
}
